name: Build and Upload Artifact
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]
 workflow_dispatch:
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v3
   - name: Setup .NET
     uses: actions/setup-dotnet@v4
     with:
       dotnet-version: '8.0.x' # adjust if needed
   - name: Restore dependencies
     run: dotnet restore ./CLI/src/Stellar.CLI/Stellar.CLI.csproj
   - name: Build
     run: dotnet build ./CLI/src/Stellar.CLI/Stellar.CLI.csproj --configuration Release --no-restore
   - name: Publish
     run: dotnet publish ./CLI/src/Stellar.CLI/Stellar.CLI.csproj --configuration Release --output ./publish
   - name: Upload artifact
     uses: actions/upload-artifact@v4
     with:
       name: stellar-path-artifact
       path: ./publish
